// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"encoding/json"
	"fmt"
	"github.com/yaien/cultural/internal/modules/configs/models"
)

func marshal(data any) string {
	bytes, _ := json.Marshal(data)
	return string(bytes)
}

func Pages() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		config := ctx.Value(models.ConfigContextKey).(*models.Config)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(fmt.Sprintf("pages({ url: %q })", config.Url))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/modules/configs/interface/web/views/pages.templ`, Line: 22, Col: 61}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><template x-if=\"ready\"><div class=\"container\"><div class=\"edit\"><div role=\"group\"><button type=\"button\">Crear</button> <button type=\"button\">Fuentes</button> <button type=\"button\">Eliminar</button> <button type=\"button\">Editor</button></div><form @submit.prevent=\"savePage()\"><fieldset><legend>Seleccionar Sitio</legend> <select name=\"page\" @change=\"select($event.target.value)\"><template x-for=\"(value, key) in pages\" :key=\"key\"><option :value=\"key\" x-text=\"value.name\"></option></template></select></fieldset><fieldset><legend>Nombre</legend> <input name=\"name\" x-model=\"data.name\" required></fieldset><fieldset><legend>Titulo</legend> <input name=\"title\" x-model=\"data.title\" required></fieldset><fieldset role=\"grop\"><legend>Url</legend> <input name=\"url\" :value=\"pageUrl\" required :disabled=\"pageUrlIsDisabled\"></fieldset><div class=\"actions\"><button type=\"submit\" :disabled=\"loading\">Guardar</button></div></form></div><div class=\"page\" x-show=\"page\" x-transition><div class=\"options\"></div><iframe :src=\"`/dashboard/api/pages/${page}/render`\"></iframe></div></div></template></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Dashboard(Options{
			Title:   "Sites",
			Path:    "/dashboard/pages",
			Scripts: []string{"/assets/static/dashboard/pages.js"},
			Styles:  []string{"/assets/static/dashboard/pages.css"},
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
