services:
  mongodb:
    image: mongo
    container_name: cultural_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: cultural
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data:
    driver: local
