name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version: "1.25"
      - name: Build Binary
        run: GOOS=linux GOARCH=amd64 go build ./cmd/cultural
      - name: Upload Artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          path: |
            cultural
            Dockerfile
  deploy:
    runs-on: ubuntu-slim
    needs: build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v7.0.0
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{secrets.SERVER_PRIVATE_KEY}}
      - name: Setup SSH Host Key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: Deploy
        run: |
          rsync -avz cultural Dockerfile cultural@142.93.80.76:deploy/
          ssh cultural@142.93.80.76 "./deploy/deploy.sh"
