# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        container: golang:1.26-alpine
        steps:
            - name: Checkout
              uses: actions/checkout@v6
            - name: Setup dependencies
              run: apk add --no-cache --update tzdata ffmpeg vips vips-tools
            - name: Cache Go modules
              uses: actions/cache@v3
              with:
                  path: /go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }
            - name: Test
              run: go test ./...
